config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users

  # resourcesを使用したルーティング
  resources :menus
  resources :menu_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :create, :edit, :update, :index, :destroy]

  # usersコントローラーの編集画面関連のルーティング
  get 'users/:id/settings' => 'users#setting', as: 'user_setting'
  get 'users/:id/delete' => 'users#delete', as: 'user_delete'

  # contactコントローラのルーティング
  resources :contacts, only: [:new] do
    collection do
      post 'send_user' => 'contacts#send_user'
      get 'sent_user' => 'contacts#sent_user'
    end
    member do
      get 'detail'
    end
  end

  # searchsコントローラーのルーティング
  get 'search/food' => 'searchs#search_food', as: 'search_food'
  get 'search/keyword' => 'searchs#keyword', as: 'keyword'
  get 'search/search_result' => 'searchs#search_result', as: 'search_result'

  #CSVインポート用のfoodsコントローラーのルーティング
  post 'import' => 'foods#import', as: 'import_foods'
  get 'import' => 'foods#data', as: 'import'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  has_many :menus
  has_many :contacts

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController

  before_action :reject_user, only: [:create]

  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_user
    @user = User.find_by(email: params[:email])
    if @user
      if (@user.valid_password?(params[:user][:password]) && (@user.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_user_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def setting
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:account_name, :height, :weight, :basal_metabolism, :target, :term, :status)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/delete.html.erb
<div class="user-delete">
  <div class="user-delete-contents">
    <h2>退会手続き</h2>
  </div>
  <div class="user-delete-container">
    <div class="user-delete-text">
      <p>
        退会を希望されますか？</br></br>

        退会手続きをされますと全てのサービスとご利用になられた情報全てが削除されます。</br>
        再度ご利用いただく際には新規登録が必要です。</br></br>

        本当に退会されますか？
      </p>
    </div>
    <div class="user-delete-btn">
      <%= link_to "退会する", user_path, method: :delete, data: {confilm: "本当に退会しますか？"}, class: "btn btn-danger" %>
      <%= link_to "退会しない", user_setting_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="user-setting">
  <div class="user-setting-contents">
    <h2>アカウント情報/身体情報/目標</h2>
  </div>
  <div class="user-setting-container">
    <%= form_with model:@user, method: :patch, local:true do |f| %>
      <table class="table table-bordered table-hover">
    <tr>
      <td class="user-table-title">アカウント名</td>
      <td class="user-table-data"><%= f.text_field :account_name %></td>
    </tr>
    <tr>
      <td class="user-table-title">身長</td>
      <td class="user-table-data"><%= f.text_field :height %> [cm]</td>
    </tr>
    <tr>
      <td class="user-table-title">体重</td>
      <td class="user-table-data"><%= f.text_field :weight %> [kg]</td>
    </tr>
    <tr>
      <td class="user-table-title">基礎代謝</td>
      <td class="user-table-data"><%= f.text_field :basal_metabolism %> [kcal/day]</td>
    </tr>
    <tr>
      <td class="user-table-title">目標体重</td>
      <td class="user-table-data"><%= f.text_field :target %> [kg]</td>
    </tr>
    <tr>
      <td class="user-table-title">期間</td>
      <td class="user-table-data"><%= f.text_field :term %> [month]</td>
    </tr>
  </table>
  <%= f.submit "保存", class: "btn btn-success" %>
<% end %>

app/views/users/setting.html.erb
<div class="setting-contents">
  <div class="setting-contents-top">
    <h2>設定項目</h2>
  </div>
  <div class="setting-contents-container">
    <%= link_to "〜アカウント情報設定〜", user_path, class: "btn btn-success setting-form" %>
    <%= link_to "〜退会手続き〜", user_delete_path, class: "btn btn-danger setting-form" %>
    <%= link_to "〜お問合せ・要望フォーム〜", new_contact_path, class: "btn btn-info setting-form" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-setting">
  <div class="user-setting-contents">
    <h2>アカウント情報/身体情報/目標</h2>
  </div>
  <div class="user-setting-container">
    <table class="table table-bordered table-hover">
      <tr>
        <td class="user-table-title">アカウント名</td>
        <td class="user-table-data"><%= @user.account_name %></td>
      </tr>
      <tr>
        <td class="user-table-title">身長</td>
        <td class="user-table-data"><%= @user.height %> [cm]</td>
      </tr>
      <tr>
        <td class="user-table-title">体重</td>
        <td class="user-table-data"><%= @user.weight %> [kg]</td>
      </tr>
      <tr>
        <td class="user-table-title">基礎代謝</td>
        <td class="user-table-data"><%= @user.basal_metabolism %> [kcal/day]</td>
      </tr>
      <tr>
        <td class="user-table-title">目標体重</td>
        <td class="user-table-data"><%= @user.target %> [kg]</td>
      </tr>
      <tr>
        <td class="user-table-title">期間</td>
        <td class="user-table-data"><%= @user.term %> [month]</td>
      </tr>
    </table>
    <%= link_to "編集", edit_user_path, class: "btn btn-success" %>
  </div>
</div>