config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users

  # resourcesを使用したルーティング
  resources :menus
  resources :menu_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :create, :edit, :update, :index, :destroy]

  # usersコントローラーの編集画面関連のルーティング
  get 'users/:id/settings' => 'users#setting', as: 'user_setting'
  get 'users/:id/delete' => 'users#delete', as: 'user_delete'

  # contactコントローラのルーティング
  resources :contacts, only: [:new] do
    collection do
      post 'send_user' => 'contacts#send_user'
      get 'sent_user' => 'contacts#sent_user'
    end
    member do
      get 'detail'
    end
  end

  # searchsコントローラーのルーティング
  get 'search/food' => 'searchs#search_food', as: 'search_food'
  get 'search/keyword' => 'searchs#keyword', as: 'keyword'
  get 'search/search_result' => 'searchs#search_result', as: 'search_result'

  #CSVインポート用のfoodsコントローラーのルーティング
  post 'import' => 'foods#import', as: 'import_foods'
  get 'import' => 'foods#data', as: 'import'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/food.rb
class Food < ApplicationRecord

  # リレーションの記述
  has_many :menu_foods

  #ここからCSVファイルインポートに関する記述
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      #IDが見つかればレコードを呼び出し、見つからなければ新しく作成
      food = find_by(id: row["id"]) || new
      #CSVからデータを取得し、設定する
      food.attributes = row.to_hash.slice(*updatable_attributes)
      food.save
    end
  end

  #インポート時に更新を許可するカラムを定義する
  def self.updatable_attributes
    ["id", "name", "protain", "fat", "carbon", "weight", "created_at", "updated_at"]
  end
  #ここまでCSVファイルインポートに関する記述

  # ここから検索関連のメソッド
  def self.food_serch_for(content)
    Food.where( 'name LIKE ?', "%#{content}%" )
  end
  # ここまで検索関連のメソッド

  # 食材のカロリーを計算するメソッド
  def food_calory_calculation(weight)
    food_calory = (protain.to_f*4 + fat.to_f*9 + carbon.to_f*4)*weight.to_f
    food_calory.round(2)
  end
  
  # 重量に対する食材の栄養素を計算するメソッド
  def food_protain_calculation(weight)
    food_protain = protain.to_f*weight.to_f
    food_protain.round(2)
  end
  
  def food_fat_calculation(weight)
    food_fat = fat.to_f*weight.to_f
    food_fat.round(2)
  end
  
  def food_carbon_calculation(weight)
    food_carbon = carbon.to_f*weight.to_f
    food_carbon.round(2)
  end

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_foods
  has_many :foods, through: :menu_foods, source: :food
  belongs_to :user
  attachment :image

  # 新規食事登録時にのトータルカロリー計算のメソッド
  def calory_calculation
    sum_calory = 0
    menu_foods.each do |menu_food|
      sum_calory += menu_food.food.food_calory_calculation(menu_food.weight)
    end
    sum_calory.to_f.round(2)
  end

  def protain_calculation
    foods.sum(:protain).to_f.round(2)
  end

  def fat_calculation
    foods.sum(:fat).to_f.round(2)
  end

  def carbon_calculation
    foods.sum(:carbon).to_f.round(2)
  end

end

app/models/menu_food.rb
class MenuFood < ApplicationRecord
  belongs_to :food
  belongs_to :menu
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  has_many :menus
  has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def send_user
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to sent_user_contacts_path
    else
      render :new
    end
  end

  def sent_user
  end

  private

  def contact_params
    params.require(:contact).permit(:object, :body, :user_id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def create
  end

  def import
    Food.import(params[:file])
    redirect_to menus_path(current_user)
  end

  def data
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/menu_foods_controller.rb
class MenuFoodsController < ApplicationController
  def new
    @records = Food.food_serch_for(params[:content])
    @menu_food = MenuFood.new
    @menu = Menu.where(menu_id: params[:menu_id])
  end

  def create
    @menu_food = MenuFood.new(menu_food_params)
    @records = Food.food_serch_for(params[:content])
    # ↑renderにより画面バック時に再検索するための記述
    if @menu_food.save
      redirect_to edit_menu_path(@menu_food.menu_id)
    else
      render :new
    end
  end

  def update
    @menu_food = MenuFood.find(params[:id])
    if @menu_food.update(menu_food_params)
    else
      render :edit
    end
  end

  def destroy
    menu_food = MenuFood.find(params[:id])
    menu_food.destroy
    redirect_to edit_menu_path(menu_food.menu_id)
  end

  private
  def menu_food_params
    params.require(:menu_food).permit(:weight, :food_id, :menu_id)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render :index
    end
  end

  def index
    @menus = Menu.where(user_id: current_user)
  end

  def edit
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    @menu_foods = MenuFood.where(menu_id: params[:id])
  end

  def show
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    @menu_foods = MenuFood.where(menu_id: params[:id])
  end

  def update
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    if @menu.update(menu_params)
      @menu_foods = MenuFood.where(menu_id: params[:id])
      redirect_to menu_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_path
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :user_id, :sum_protain, :sum_fat, :sum_carbon, :sum_calory, :image)
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  # def search_food
    # @records = Food.food_serch_for(params[:content])
    # @menu_food = MenuFood.new
  # end

  def keyword

  end

  def search_result
    @records = Food.food_serch_for(params[:content])
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def setting
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:account_name, :height, :weight, :basal_metabolism, :target, :term, :status)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/menu_foods_helper.rb
module MenuFoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contacts/contact.html.erb
<h2>お問合せ・要望フォーム</h2>
<%= form_with model: @contact, url: send_path, local: true do |f| %>
  <p>・どちらの内容を入力しますか？</p>
  <%= f.radio_button :object, '0' %>
  <%= f.label :object, "お問合せ" %>
  <%= f.radio_button :object, '1' %>
  <%= f.label :object, "要望" %>
  <p>・詳細を下記フォームにご入力ください。</p>
  <%= f.text_area :body, size: "80x10" %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.submit "送信" %>
<% end %>

app/views/contacts/new.html.erb
<div class="contact">
  <div class="contact-contents">
    <h2>お問合せ・要望フォーム</h2>
  </div>
  <div class="contact-container">
    <%= form_with model: @contact, url: send_user_contacts_path, local: true do |f| %>
      <div class="contact-object">
        <p>どちらの内容を入力しますか？</p>
        <%= f.radio_button :object, '0' %>
        <%= f.label :object, "お問合せ" %>
        <%= f.radio_button :object, '1' %>
        <%= f.label :object, "要望" %>
      </div>
      <div class="contact-detail">
        <p>詳細を下記フォームにご入力ください。</p>
        <%= f.text_area :body, size: "80x10" %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
      </div>
      <div class="contact-submit">
        <%= f.submit "送信", class: "btn btn-success" %>
      </div>
    <% end %>
  </div>
</div>

app/views/contacts/sent.html.erb
<p>内容を送信しました。</p>
<p>ご入力いただきました内容は弊社にて確認ののち、お客様の登録先メールアドレスにご連絡いたします。</p>
<p>ご返答に数日かかることがございますがどうぞよろしくお願い申し上げます。</p>

app/views/contacts/sent_user.html.erb
<div class="contact-finish">
  <div class="contact-finish-text">
    <p>
      内容を送信しました。</br></br>
      ご入力いただきました内容は弊社にて確認ののち、お客様の登録先メールアドレスにご連絡いたします。</br>
      ご返答に数日かかることがございますがどうぞよろしくお願い申し上げます。
    </p>
  </div>
  <div class="contact-link">
    <%= link_to "TOPへ戻る", root_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/foods/data.html.erb
<div class="food-contents">
  <div class="food-contents-top">
    <h2>食材追加</h2>
  </div>
  <div class="food-contents-container">
    <p>↓CSVファイルからの食材追加はこちら↓</br>※デフォルトで2192種類の食材データが登録されております</p>
    <%= form_with url: import_foods_path do |f| %>
      <%= f.file_field :file, accept: '.csv' %></br></br>
      <%= f.submit "アップロード", class: "btn btn-success" %>
    <% end %>
    <div class="csv-demo">
      <p>CSVデータを追加する際は1行目を下図の通り作成してください</p>
      <%= image_tag 'csv-demo.jpg', size: '770x420' %>
    </div>
  </div>
</div>

app/views/foods/import.html.erb
<%= form_with url: import_foods_path do |f| %>
  <%= f.file_field :file, accept: '.csv' %>
  <%= f.submit "アップロード" %>
<% end %>

app/views/menu_foods/new.html.erb
<!--search_food,html,erbより転載。記述はparams:[menu_id]の行の有無-->
<div class="search-food">
<h2>検索結果</h2>
<p>※表示値は全て100g当たりの値となります</p>
<div class="search-food-table">
<table class="table table-bordered table-hover">
  <tr>
    <th class="search-food-head">食材名</th>
    <th class="search-food-head2">タンパク質 [g]</th>
    <th class="search-food-head2">脂質 [g]</th>
    <th class="search-food-head2">炭水化物 [g]</th>
    <th class="search-food-head3">人前</th>
    <th class="search-food-head3"></th>
  </tr>
  <% @records.each do |food| %>
    <tr>
      <%= form_with model: @menu_food, url: menu_foods_path, local: true do |f| %>
        <td><%= food.name %></td>
        <td class="search-food-data"><%= food.protain %></td>
        <td class="search-food-data"><%= food.fat %></td>
        <td class="search-food-data"><%= food.carbon %></td>
        <td class="search-food-data"><%= f.text_field :weight, :size => "5" %></td>
        <%= f.hidden_field :food_id, :value => food.id %>
        <%= f.hidden_field :menu_id, :value => params[:menu_id] %>
        <td class="search-food-data"><%= f.submit '登録', class: "btn btn-success" %></td>
      <% end %>
    </tr>
  <% end %>
</table>
</div>
</div>

app/views/menu_foods/update.js.erb
$('#menu_food_<%= @menu_food.id %>').html("<%= j(render 'menus/update-btn', menu_food: @menu_food) %>");

app/views/menus/_update-btn.html.erb
<td class="menu-edit-table-data"><%= menu_food.food.name %></td>
<td class="menu-edit-table-data2"><%= menu_food.food.food_protain_calculation(menu_food.weight) %></td>
<td class="menu-edit-table-data2"><%= menu_food.food.food_fat_calculation(menu_food.weight) %></td>
<td class="menu-edit-table-data2"><%= menu_food.food.food_carbon_calculation(menu_food.weight) %></td>
<td class="menu-edit-table-data2"><%= menu_food.food.food_calory_calculation(menu_food.weight) %></td>
<%= form_with model: menu_food, method: :patch, remote: true, id: "menu_food_form_#{menu_food.id}" do |f| %>
  <input value="patch" form="<%= "menu_food_form_#{menu_food.id}" %>" type="hidden" name="_method">
  <td class="menu-edit-table-data3"><%= f.text_field :weight, :size => "5", form: "menu_food_form_#{menu_food.id}" %></td>
  <td class="menu-edit-table-data3"><%= f.submit "変更", class: "btn btn-success", form: "menu_food_form_#{menu_food.id}" %></td>
<% end %>
<td class="menu-edit-table-data3"><%= link_to "削除", menu_food_path(menu_food), method: :delete, class: "btn btn-danger" %></td>

app/views/menus/edit.html.erb
<div class="menu-edit">
  <h2>登録・編集</h2>
  <div class="menu-search">
    <!--食材検索-->
    <%= form_with model: @menu_food, url:new_menu_food_path, method: :get, local:true do |f| %>
      <p>
        検索したい食材を<strong>"ひらがな"</strong>で入力してください。</br>
        食材検索 : <%= f.text_field :content %>
        <%= f.hidden_field :menu_id, :value => params[:id] %>
        <%= f.submit "検索", class: "btn btn-primary" %>
      </p>
    <% end %>
  </div>
  <div class="menu-edit-table">
    <!--食材栄養素一覧-->
    <table class="table table-bordered table-hover">
      <tr>
        <th class="menu-edit-table-data">食材名</th>
        <th class="menu-edit-table-data2">タンパク質 [g]</th>
        <th class="menu-edit-table-data2">脂質 [g]</th>
        <th class="menu-edit-table-data2">炭水化物 [g]</th>
        <th class="menu-edit-table-data2">カロリー [kcal]</th>
        <th class="menu-edit-table-data3">人前</th>
        <th class="menu-edit-table-data3"></th>
        <th class="menu-edit-table-data3"></th>
      </tr>
      <% @menu_foods.each do |menu_food| %>
        <tr id="menu_food_<%= menu_food.id %>">
          <%= render 'menus/update-btn', menu_food: menu_food %>
          <%#= render 'menus/delete-btn', menu_food: menu_food %>
        </tr>
      <% end %>
    </table>
  </div>

  <%= form_with model: @menu, method: :patch, local:true do |f| %>
    <div>
      <h5>栄養素合計</h5>
      <div class="menu-edit-table">
        <table class="table table-bordered table-hover">
          <tr>
            <th class="menu-edit-table-sum">タンパク質 [g]</th>
            <th class="menu-edit-table-sum">脂質 [g]</th>
            <th class="menu-edit-table-sum">炭水化物 [g]</th>
            <th class="menu-edit-table-sum">カロリー [kcal]</th>
          </tr>
          <tr>
            <td class="menu-edit-table-sum"><%= @menu.protain_calculation %></td>
            <td class="menu-edit-table-sum"><%= @menu.fat_calculation %></td>
            <td class="menu-edit-table-sum"><%= @menu.carbon_calculation %></td>
            <td class="menu-edit-table-sum"><%= @menu.calory_calculation %></td>
          </tr>
        </table>
      </div>
    </div>
    <div>
      <p>食事名 : <%= f.text_field :name %></p>
    </div>
    <div class="menu-edit-image">
      <%= attachment_image_tag @menu, :image, :fill, 200, 200, format: 'jpeg' %>
      <%= f.attachment_field :image %>
    </div>
    <%= f.submit "保存", class: "btn btn-success" %>
    <%= link_to "削除", menu_path, method: :delete, class: "btn btn-danger" %>
  <% end %>
</div>

app/views/menus/index.html.erb
<div class="menu">
  <div class="menu-contents">
    <h2>メニュー一覧</h2>
  </div>
  <div class="menu-containers">
    <div class="menu-container-link">
      <%= link_to "新規登録", new_menu_path, class: "btn btn-warning" %>
    </div>
    <div class="menu-container">
      <% @menus.each do |menu| %>
        <div class="menu-container-item">
          <%= attachment_image_tag menu, :image, :fill, 200, 200, format: 'jpeg' %>
          <p>レシピ名:<%= menu.name %></p>
          <p>p:<%= menu.protain_calculation %> [g] / f:<%= menu.fat_calculation %> [g] / c:<%= menu.carbon_calculation %> [g]</p>
          <p>総カロリー:<%= menu.calory_calculation %></p>
          <%= link_to "詳細", menu_path(menu), class: "btn btn-primary" %>
          <%= link_to "編集", edit_menu_path(menu), class: "btn btn-success" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/menus/new.html.erb
<div class="menu">
  <div class="menu-contents">
    <h2>レシピ登録</h2>
  </div>
  <div class="menu-new-container">
    <%= form_with model: @menu, url: menus_path, method: :post, local: true do |f| %>
      <p>レシピ名 : <%= f.text_field :name %> </p>
      <p>料理画像 : <%= f.attachment_field :image %> </p>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <p>※食材追加はレシピ登録後、レシピ編集画面より行えます。</p>
      <%= f.submit "登録", class: "btn btn-success" %>
    <% end %>
  </div>
</div>

app/views/menus/show.html.erb
<div class="menu-show">
  <h2>詳細</h2>
  <div class="menu-show-contents">
    <p class="menu-show-name">レシピ名 : <%= @menu.name %></p>
    <p class="menu-show-image"><%= attachment_image_tag @menu, :image, :fill, 200, 200, format: 'jpeg' %></p>
  </div>
  <p>食材一覧</p>
  <div class="menu-show-table">
    <table class="table table-bordered table-hover">
      <tr>
        <th class="menu-show-table-data">食材名</th>
        <th class="menu-show-table-data2">タンパク質 [g]</th>
        <th class="menu-show-table-data2">脂質 [g]</th>
        <th class="menu-show-table-data2">炭水化物 [g]</th>
        <th class="menu-show-table-data2">人前</th>
        <th class="menu-show-table-data2">カロリー [kcal]</th>
      </tr>
      <% @menu_foods.each do |menu_food| %>
        <tr>
          <td class="menu-show-table-data"><%= menu_food.food.name %></td>
          <td class="menu-show-table-data2"><%= menu_food.food.protain %></br>
          <td class="menu-show-table-data2"><%= menu_food.food.fat %></td>
          <td class="menu-show-table-data2"><%= menu_food.food.carbon %></td>
          <td class="menu-show-table-data2"><%= menu_food.weight %></td>
          <td class="menu-show-table-data2"><%= menu_food.food.food_calory_calculation(menu_food.weight) %></td>
        </tr>
      <% end %>
    </table>
  </div>
  <p>栄養素合計</p>
  <div class="menu-show-table">
    <table class="table table-bordered table-hover">
      <tr>
        <th class="menu-show-table-sum">タンパク質 [g]</th>
        <th class="menu-show-table-sum">脂質 [g]</th>
        <th class="menu-show-table-sum">炭水化物 [g]</th>
        <th class="menu-show-table-sum">カロリー [kcal]</th>
      </tr>
      <tr>
        <td class="menu-show-table-sum"><%= @menu.foods.sum(:protain).to_f.round(2) %></td>
        <td class="menu-show-table-sum"><%= @menu.fat_calculation %></td>
        <td class="menu-show-table-sum"><%= @menu.foods.sum(:carbon).to_f.round(2) %></td>
        <td class="menu-show-table-sum"><%= @menu.calory_calculation %></td>
      </tr>
    </table>
  </div>
  <%= link_to "編集", edit_menu_path, class: "btn btn-success" %>
  <%= link_to "削除", menu_path, method: :delete, class: "btn btn-danger" %>
</div>