config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  devise_for :users

  # resourcesを使用したルーティング
  resources :menus
  resources :menu_foods, only: [:new, :create, :edit, :update, :destroy]
  resources :users, only: [:show, :create, :edit, :update, :index, :destroy]

  # usersコントローラーの編集画面関連のルーティング
  get 'users/:id/settings' => 'users#setting', as: 'user_setting'
  get 'users/:id/delete' => 'users#delete', as: 'user_delete'

  # contactコントローラのルーティング
  resources :contacts, only: [:new] do
    collection do
      post 'send_user' => 'contacts#send_user'
      get 'sent_user' => 'contacts#sent_user'
    end
    member do
      get 'detail'
    end
  end

  # searchsコントローラーのルーティング
  get 'search/food' => 'searchs#search_food', as: 'search_food'
  get 'search/keyword' => 'searchs#keyword', as: 'keyword'
  get 'search/search_result' => 'searchs#search_result', as: 'search_result'

  #CSVインポート用のfoodsコントローラーのルーティング
  post 'import' => 'foods#import', as: 'import_foods'
  get 'import' => 'foods#data', as: 'import'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
end

app/models/food.rb
class Food < ApplicationRecord

  # リレーションの記述
  has_many :menu_foods

  #ここからCSVファイルインポートに関する記述
  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      #IDが見つかればレコードを呼び出し、見つからなければ新しく作成
      food = find_by(id: row["id"]) || new
      #CSVからデータを取得し、設定する
      food.attributes = row.to_hash.slice(*updatable_attributes)
      food.save
    end
  end

  #インポート時に更新を許可するカラムを定義する
  def self.updatable_attributes
    ["id", "name", "protain", "fat", "carbon", "weight", "created_at", "updated_at"]
  end
  #ここまでCSVファイルインポートに関する記述

  # ここから検索関連のメソッド
  def self.food_serch_for(content)
    Food.where( 'name LIKE ?', "%#{content}%" )
  end
  # ここまで検索関連のメソッド

  # 食材のカロリーを計算するメソッド
  def food_calory_calculation(weight)
    food_calory = (protain.to_f*4 + fat.to_f*9 + carbon.to_f*4)*weight.to_f
    food_calory.round(2)
  end
  
  # 重量に対する食材の栄養素を計算するメソッド
  def food_protain_calculation(weight)
    food_protain = protain.to_f*weight.to_f
    food_protain.round(2)
  end
  
  def food_fat_calculation(weight)
    food_fat = fat.to_f*weight.to_f
    food_fat.round(2)
  end
  
  def food_carbon_calculation(weight)
    food_carbon = carbon.to_f*weight.to_f
    food_carbon.round(2)
  end

end

app/models/menu.rb
class Menu < ApplicationRecord
  has_many :menu_foods
  has_many :foods, through: :menu_foods, source: :food
  belongs_to :user
  attachment :image

  # 新規食事登録時にのトータルカロリー計算のメソッド
  def calory_calculation
    sum_calory = 0
    menu_foods.each do |menu_food|
      sum_calory += menu_food.food.food_calory_calculation(menu_food.weight)
    end
    sum_calory.to_f.round(2)
  end

  def protain_calculation
    foods.sum(:protain).to_f.round(2)
  end

  def fat_calculation
    foods.sum(:fat).to_f.round(2)
  end

  def carbon_calculation
    foods.sum(:carbon).to_f.round(2)
  end

end

app/models/menu_food.rb
class MenuFood < ApplicationRecord
  belongs_to :food
  belongs_to :menu
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  has_many :menus
  has_many :contacts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end

  def send_user
    @contact = Contact.new(contact_params)
    if @contact.save
      redirect_to sent_user_contacts_path
    else
      render :new
    end
  end

  def sent_user
  end

  private

  def contact_params
    params.require(:contact).permit(:object, :body, :user_id)
  end

end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def create
  end

  def import
    Food.import(params[:file])
    redirect_to menus_path(current_user)
  end

  def data
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/menu_foods_controller.rb
class MenuFoodsController < ApplicationController
  def new
    @records = Food.food_serch_for(params[:content])
    @menu_food = MenuFood.new
    @menu = Menu.where(menu_id: params[:menu_id])
  end

  def create
    @menu_food = MenuFood.new(menu_food_params)
    @records = Food.food_serch_for(params[:content])
    # ↑renderにより画面バック時に再検索するための記述
    if @menu_food.save
      redirect_to edit_menu_path(@menu_food.menu_id)
    else
      render :new
    end
  end

  def update
    @menu_food = MenuFood.find(params[:id])
    if @menu_food.update(menu_food_params)
    else
      render :edit
    end
  end

  def destroy
    menu_food = MenuFood.find(params[:id])
    menu_food.destroy
    redirect_to edit_menu_path(menu_food.menu_id)
  end

  private
  def menu_food_params
    params.require(:menu_food).permit(:weight, :food_id, :menu_id)
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  def new
    @menu = Menu.new
  end

  def create
    @menu = Menu.new(menu_params)
    if @menu.save
      redirect_to menus_path
    else
      render :index
    end
  end

  def index
    @menus = Menu.where(user_id: current_user)
  end

  def edit
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    @menu_foods = MenuFood.where(menu_id: params[:id])
  end

  def show
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    @menu_foods = MenuFood.where(menu_id: params[:id])
  end

  def update
    @menu = Menu.find_by(user_id: current_user.id, id: params[:id])
    if @menu.update(menu_params)
      @menu_foods = MenuFood.where(menu_id: params[:id])
      redirect_to menu_path(params[:id])
    else
      render :edit
    end
  end

  def destroy
    menu = Menu.find(params[:id])
    menu.destroy
    redirect_to menus_path
  end

  private
  def menu_params
    params.require(:menu).permit(:name, :user_id, :sum_protain, :sum_fat, :sum_carbon, :sum_calory, :image)
  end

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  # def search_food
    # @records = Food.food_serch_for(params[:content])
    # @menu_food = MenuFood.new
  # end

  def keyword

  end

  def search_result
    @records = Food.food_serch_for(params[:content])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def setting
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def index
  end

  def create
  end

  def update
    @user = User.find(params[:id])
    @user.update!(user_params)
    redirect_to user_path(current_user.id)
  end

  def destroy
    @user = User.find(params[:id])
    @user.update(is_deleted: true)
    reset_session
    flash[:notice] = "ありがとうございました。またのご利用を心よりお待ちしております。"
    redirect_to root_path
  end


  private

  def user_params
    params.require(:user).permit(:account_name, :height, :weight, :basal_metabolism, :target, :term, :status)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/menu_foods_helper.rb
module MenuFoodsHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div class="top">
  <h1 class="top-text">Meal Balance Checker</h1>
</div>
<div class="top-container">
  <div class="top-explain">
    <h3>~Meal Balance Checkerとは~</h3>
    </br></br></br><p>体重を増やしたい、減らしたい</p>
    <p>Meal Balance Checkerでは理想の自分に近づくためのお手伝いをさせていただきます。</p></br></br></br>
    <p>私たちは「食事の栄養素の確認を簡単に」をコンセプトに</p>
    <p>栄養素確認サービスを提供しています。</p>
    <p>料理の素材を入力することで、栄養成分がどの程度含まれているのかが確認できます。</p></br></br></br>
    <p>タンパク質、脂質、炭水化物をコントロールしたいときにぜひご利用ください。</p>
  </div>
  <div class="top-demo">
    <p>メニュー詳細画面デモ</p>
    <%= image_tag 'demo.jpg', size: '720x400' %>
  </div>
    <h3 class="top-signup"><%= link_to "新規登録はこちら", new_user_registration_path, class: "btn btn-success" %></h3>

  <div class="top-question">
    <p>〜よくある質問集〜</p>
      <div class="top-question-container">
        <p>Q. コンテンツは有料でしょうか？</p>
        <p>  A. いいえ、無料でご利用できます。</p>
        <p>Q. 検索可能な食材はどれくらいあるのでしょうか？</p>
        <p>  A. 2192個の食材が登録されております。栄養成分は全て政府より提供されておりますデータから引用しております。</p>
      </div>
  </div>
</div>

app/views/searchs/keyword.html.erb
<div class="search">
<h2>食材検索</h2>
<p>検索したい食材を<strong>"ひらがな"</strong>で入力してください</p>
<%= form_with url: search_result_path, method: :get, local: true do |f| %>
  <%= f.text_field :content %>
  <%= f.submit "検索", class: "btn btn-secondary" %>
<% end %>
</div>

app/views/searchs/search_result.html.erb
<div class="search-food">
  <h2>検索結果</h2>
  <p>※表示値は全て100g当たりの成分値となります</p>
  <div class="search-food-table">
    <table class="table table-bordered table-hover">
      <tr>
        <th class="search-food-head">食材名</th>
        <th class="search-food-head2">タンパク質 [g]</th>
        <th class="search-food-head2">脂質 [g]</th>
        <th class="search-food-head2">炭水化物 [g]</th>
      </tr>
      <% @records.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td class="search-food-data"><%= food.protain %></td>
          <td class="search-food-data"><%= food.fat %></td>
          <td class="search-food-data"><%= food.carbon %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>